name: Create comment on issue

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "check dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
