name: Hello-World-workflow

on:
  push:
    branches: -master
  pull_request:
    branches: -master
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: print hello Bilal Nazir
        run: echo "Hello Bilal"
        shell: bash

  job-name2:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye
        run: echo "Goodbye bilal"
        shell: bash
